# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    resolvers:
        default:
            web_path: ~

    filter_sets:
        notification_thumbnail:
            quality: 75
            filters:
                thumbnail:
                    size: [50, 50]
                    mode: outbound
